// Zentrale Sammlung aller PocketBase-Collection-Namen. Die Werte müssen exakt
// mit den Namen in scripts/pocketbase-setup.mjs übereinstimmen.
export const COL = {
  users: "users",
  uploads: "uploads",
  genres: "genres",
  tags: "tags",
  series: "series",
  seasons: "seasons",
  episodes: "episodes",
  movies: "movies",
  ratings: "ratings",
  watchHistory: "watch_history",
  watchlistItems: "watchlist_items",
  subscriptions: "subscriptions",
  notifications: "notifications",
  userCollections: "user_collections",
  collectionItems: "collection_items",
  forumCategories: "forum_categories",
  forumThreads: "forum_threads",
  forumPosts: "forum_posts",
  tickets: "tickets",
  ticketMessages: "ticket_messages",
  profileFavorites: "profile_favorites",
} as const;
